FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/*
WORKDIR .
COPY Web/dist/ /usr/share/nginx/html

CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]
